kind: ConfigMap
apiVersion: v1
metadata:
  name: resources
  namespace: test-pods
data:
  boskos-resources.yaml: |
    resources:
      - type: "powervs-service"
        state: dirty
        names:
        - "k8s-boskos-powervs-lon04-00"
        - "k8s-boskos-powervs-lon04-01"
        - "k8s-boskos-powervs-lon06-00"
      - type: "powervs-k8s-conformance"
        state: dirty
        names:
        - "k8s-infra-boskos-osa21-02"
      - type: "vpc-service"
        state: dirty
        names:
        - "k8s-boskos-vpc-br-sao-00"
        - "k8s-boskos-vpc-br-sao-01"
        - "k8s-boskos-vpc-jp-osa-00"
