apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3-hmac-credentials
  namespace: test-pods
spec:
  refreshInterval: 60m
  secretStoreRef:
    name: secretstore-ibm-k8s-infra
    kind: ClusterSecretStore
  target:
    name: s3-hmac-credentials
    creationPolicy: Owner
  data:
  - secretKey: hmac_credentials
    remoteRef:
      key: service_credentials/25618a7b-97cf-19cf-7b12-c6129414545e
