presubmits:
  ppc64le-cloud/test-infra:
  - name: pull-test-infra-yamllint
    always_run: true
    decorate: true
    spec:
      containers:
        - image: quay.io/powercloud/yamllint:1.34.0
          command:
            - yamllint
            - -c
            - config/jobs/.yamllint.conf
            - config/jobs
            - config/prow/cluster
            - config/prow/labels.yaml
    annotations:
      testgrid-dashboards: presubmits-test-infra
      testgrid-tab-name: verify-yaml
  - name: pull-test-infra-prow-checkconfig
    decorate: true
    run_if_changed: '^(config/prow/(config|plugins).yaml$|config/jobs/.*.yaml$)'
    spec:
      containers:
      - image: us-docker.pkg.dev/k8s-infra-prow/images/checkconfig:v20250307-7a867cddc
        command:
        - checkconfig
        args:
        - --config-path=config/prow/config.yaml
        - --job-config-path=config/jobs
        - --plugin-config=config/prow/plugins.yaml
        - --strict
        - --warnings=mismatched-tide-lenient
        - --warnings=tide-strict-branch
        - --warnings=needs-ok-to-test
        - --warnings=validate-owners
        - --warnings=missing-trigger
        - --warnings=validate-urls
        - --warnings=unknown-fields
        - --warnings=duplicate-job-refs
    annotations:
      testgrid-dashboards: presubmits-test-infra
